#!/bin/sh
# List when rpms were installed.
#
# rpm -q --querytags | sort
# rpm -qa --queryformat='%{INSTALLTIME} %-30{NAME}%-20{INSTALLTIME:date}\n' | sort +0 -n

rpm -qa --queryformat='%{INSTALLTIME}\t%{INSTALLTIME:date}\t%{NAME}-%{VERSION}-%{RELEASE}\n' | \
    sort -n | \
    cut -f2-
