#!/bin/sh
# Find when rpms were installed.
#
# rpm -q --querytags | sort

#rpm -qa --queryformat='%{INSTALLTIME} %-30{NAME}%-20{INSTALLTIME:date}\n' | sort +0 -n

rpm -qa --queryformat='%{INSTALLTIME}\t%{NAME}-%{VERSION}-%{RELEASE}\t%{INSTALLTIME:date}\n' | \
    sort -n | \
    cut -d '	' -f2- | \
    column -s '	' -t | \
    cat
